### ISSUE TITLE
UNEDTrivial Moodle Docs page in Spanish and English

### ISSUE THREAD

**Issue by germanvaleroelizondo** [jcastello46/moodle-mod_unedtrivial#2]
Hi,

I hope you don't mind that I made a few changes to https://docs.moodle.org/34/en/UNEDTrivial .

I also added a new page at https://docs.moodle.org/all/es/UNEDTrivial . You might want to change the images for a true Spanish screen image.

Please feel free to add/remove/change as needed.

Saludos desde México

**Comment by jcastello46** [comment]
Sin problema :)
Saludos!
